#line 2 "jscript_massager.cc"
#line 5 "jscript_massager.l"
/*
  Copyright 2007 Google Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

#include <string>
#include <vector>

// The following includes are used in flex generated source. Because we use
// namespaces, include them first to avoid namespace errors when these files
// are included from flex generated source.
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <inttypes.h>

#include <ggadget/common.h>

// These macros make the '{' and '}' paired in flex source code.
#define BEGIN_NS(ns) namespace ns {
#define END_NS }

BEGIN_NS(ggadget)
BEGIN_NS(smjs)




#line 44 "jscript_massager.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 31
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[272] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   32,   30,   28,    2,   30,    7,
       18,   19,   28,   30,   30,   30,   30,   19,    4,    3,
       30,   30,    9,    8,   30,   17,   17,   14,   17,   17,
       21,   21,   21,   21,   23,   23,   22,   23,    0,   26,
        0,    0,   24,    0,    0,   25,    0,    0,    0,    1,
        6,    0,    0,    0,    0,    0,    5,   10,    0,   14,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   20,    0,   22,    0,    0,    0,   27,
        0,    0,    0,    0,    0,    0,    0,    0,   11,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   11,    0,    0,
        0,    0,    0,   11,    0,    0,    0,    0,    0,   11,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       11,    0,    0,   11,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   11,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   11,    0,    0,    0,   11,    0,
        0,    0,    0,    0,    0,   29,    0,    0,    0,    0,
        0,    0,   15,    0,    0,    0,    0,    0,    0,   13,
        0,    0,   29,    0,   29,    0,    0,    0,   12,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       16,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    5,    6,    7,
        8,    9,    5,   10,    1,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    5,   14,    5,
       15,    5,    5,    1,   16,   13,   13,   17,   18,   19,
       13,   13,   20,   13,   13,   21,   22,   13,   13,   13,
       13,   13,   13,   23,   24,   25,   13,   13,   13,   13,
       26,   27,   28,    5,   13,    1,   16,   13,   13,   17,

       29,   19,   13,   13,   30,   13,   13,   31,   22,   32,
       33,   34,   13,   13,   35,   36,   24,   25,   13,   13,
       13,   13,   37,    5,   38,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[39] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[350] =
    {   0,
        0,    0,   36,   38,   40,   41,  603,  602,   59,   70,
       72,   76,   52,   57,  613,  616,   90,  616,   94,  616,
      616,  616,  616,  101,  579,   45,   23,  105,  616,  616,
       71,    0,  616,  616,    0,  616,  109,  616,  120,   77,
      616,  112,  116,    0,  616,  127,  131,  126,    0,  616,
      132,  143,  145,  140,  151,  156,  602,  153,  576,  616,
      616,  573,  158,  155,  171,  605,  616,  616,  173,  616,
        0,  157,    0,  169,   80,   22,  598,  603,  184,  170,
        0,  596,  601,  616,  186,  189,  181,  594,  599,  616,
      592,  597,  590,  595,  185,  588,  193,  593,  616,   91,

      592,  558,  563,  583,  588,  201,  197,  559,  580,  585,
      578,  583,  566,  113,  575,  198,  580,  209,  573,  578,
      571,  205,  576,  216,  569,  574,  567,  213,  572,  221,
      565,  217,  570,  563,  223,  568,  561,  566,  559,  168,
      558,  231,  563,  234,  535,  531,  554,  229,  559,  552,
      557,  524,  549,  230,  554,  547,  235,  552,  538,  531,
      543,  542,  236,  547,  540,  539,  240,  544,  537,  536,
      535,  534,  241,  539,  532,  242,  252,  531,  254,  506,
      506,  528,  527,  250,  532,  505,  524,  523,  507,  261,
      521,  258,  520,  519,  260,  518,  517,  262,  516,  266,

      515,  267,  514,  274,  513,  277,  512,  272,  285,  282,
      488,  484,  509,  281,  508,  293,  507,  289,  506,  290,
      105,  301,  616,  297,  505,  298,  504,  302,  477,  616,
      502,  303,  314,  309,  616,  172,  501,  506,  616,  499,
      504,  481,  496,  310,  501,  494,  311,  343,  321,  326,
      291,  261,  256,  315,  251,  316,  234,  311,  329,  331,
      616,  330,  218,  212,  142,  335,  115,   81,   76,  336,
      616,  348,  350,  352,  354,  356,  358,   75,  360,  362,
      364,  366,  368,  370,  372,  374,  376,  378,  380,  382,
      384,  386,  388,  390,  392,  394,  396,  398,  400,  402,

      404,  406,  408,  410,  412,  414,  416,  418,  420,  422,
      424,  426,  428,  430,  432,  434,  436,  438,  440,  442,
      444,  446,  448,  450,  452,  454,  456,  458,  460,  462,
      464,  466,  468,  470,  472,  474,  476,  478,  480,  482,
      484,  486,  488,  490,  492,  494,  496,  498,  500
    } ;

static yyconst flex_int16_t yy_def[350] =
    {   0,
      271,    1,  272,  272,  272,  272,  272,  272,  273,  273,
      274,  274,  275,  275,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  276,  271,  271,  277,  271,  271,  271,  271,  271,
      271,  271,  271,  278,  271,  271,  271,  271,   17,  271,
      279,  271,  271,  271,  271,  271,  280,  281,  271,  271,
      271,  271,  271,  271,  271,  281,  271,  271,  271,  271,
       39,  271,   39,  271,  271,  271,  282,  283,  271,  271,
      278,  284,  285,  271,  271,  271,  271,  286,  287,  271,
      288,  289,  290,  291,  271,  280,  292,  281,  271,  293,

      294,  271,  271,  295,  296,  271,  271,  271,  297,  298,
      299,  300,  271,  271,  282,  301,  283,  271,  302,  303,
      284,  304,  285,  271,  305,  306,  286,  307,  287,  271,
      288,  308,  289,  290,  309,  291,  310,  311,  312,  293,
      310,  313,  294,  271,  271,  271,  295,  314,  296,  315,
      316,  271,  297,  317,  298,  299,  318,  300,  271,  271,
      319,  302,  320,  303,  321,  305,  322,  306,  323,  324,
      325,  310,  326,  311,  312,  292,  327,  328,  281,  271,
      271,  329,  315,  330,  316,  271,  331,  332,  271,  271,
      319,  333,  334,  321,  335,  336,  323,  307,  324,  308,

      325,  309,  328,  327,  328,  313,  328,  326,  271,  281,
      271,  271,  329,  314,  337,  271,  331,  317,  332,  318,
      271,  271,  271,  271,  334,  320,  336,  322,  271,  271,
      337,  330,  271,  271,  271,  271,  338,  339,  271,  340,
      341,  271,  338,  342,  339,  340,  343,  341,  271,  344,
      345,  271,  344,  342,  345,  343,  271,  271,  271,  271,
      271,  271,  346,  347,  346,  348,  347,  349,  349,  348,
        0,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271
    } ;

static yyconst flex_int16_t yy_nxt[655] =
    {   0,
       16,   16,   17,   18,   19,   20,   21,   22,   19,   23,
       19,   24,   25,   23,   19,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   21,   26,   22,   25,   25,
       25,   25,   27,   25,   25,   25,   21,   28,   29,   30,
       29,   30,   33,   33,  114,   34,   34,   31,   60,   31,
       61,   31,   31,   46,   47,   59,   62,  114,   46,   47,
       37,   37,   32,   48,   32,   38,   35,   35,   48,   39,
       40,   37,   37,   42,   42,   84,   38,   42,   42,   57,
       39,   40,   66,   43,  270,   77,   44,   43,   78,  270,
       44,   49,   49,  141,   50,   52,   53,  113,   50,  142,

       50,   51,   55,   56,   50,   54,   63,   63,  113,   57,
       69,   69,   58,   79,   79,   70,   64,  260,   65,   71,
       72,   73,   73,   80,   82,  236,   81,   83,   85,   86,
      160,   74,   85,   86,   88,  236,   75,   89,   87,   76,
       91,  160,   87,   92,   52,   53,   52,   53,   93,   76,
      266,   94,   55,   56,   54,   99,   54,   55,   56,   63,
       63,  100,   95,  104,  101,  109,  105,   95,  110,   64,
      141,   65,  106,  106,   69,   69,  142,  111,  119,   70,
      112,  120,  107,   71,   72,   79,   79,   85,   86,  125,
       85,   86,  126,  137,  242,   80,  138,   87,   81,  108,

       87,   97,  106,  106,   99,  150,  116,  242,  151,  118,
       69,   69,  107,  122,  260,   70,  124,   79,   79,   71,
       72,  128,   85,   86,  130,  132,  266,   80,   49,  108,
       81,  135,   87,  178,   52,   55,   56,  148,  154,  142,
       63,   69,  179,  157,  163,   95,   73,   79,  167,  173,
      176,   85,   55,   99,  205,  179,  209,  258,  184,  256,
      206,  106,  222,  222,  254,  210,  192,  223,  195,  118,
      198,  124,  224,  130,  200,  202,  205,   49,   52,  178,
      208,  257,  206,   55,   99,  206,   55,   56,  179,  214,
      100,  257,   63,  101,  233,  233,   95,  218,  220,  256,

       69,   73,  222,  222,  234,  237,  226,  223,  238,   79,
      228,  232,  224,   85,  106,  233,  233,  240,  244,  247,
      241,  222,  233,  254,  256,  234,  222,  233,  259,  235,
      260,  260,  260,  260,  254,  261,  252,  261,  263,  259,
      262,  264,  262,  266,  270,  233,  260,  260,   16,   16,
       36,   36,   41,   41,   45,   45,   67,   67,   68,   68,
       90,   90,   96,   96,   98,   98,  115,  115,  117,  117,
      121,  121,  123,  123,  127,  127,  129,  129,  131,  131,
      133,  133,  134,  134,  136,  136,  139,  139,  140,  140,
      143,  143,  147,  147,  149,  149,  153,  153,  155,  155,

      156,  156,  158,  158,  161,  161,  162,  162,  164,  164,
      165,  165,  166,  166,  168,  168,  169,  169,  170,  170,
      171,  171,  172,  172,  174,  174,  175,  175,  177,  177,
      182,  182,  183,  183,  185,  185,  187,  187,  188,  188,
      191,  191,  193,  193,  194,  194,  196,  196,  197,  197,
      199,  199,  201,  201,  203,  203,  204,  204,  207,  207,
      213,  213,  215,  215,  217,  217,  219,  219,  161,  161,
      225,  225,  165,  165,  227,  227,  231,  231,  243,  243,
      245,  245,  246,  246,  248,  248,  250,  250,  251,  251,
      253,  253,  255,  255,  265,  265,  267,  267,  268,  268,

      269,  269,  247,  222,  244,  249,  233,  247,  222,  244,
      232,  239,  228,  226,  220,  218,  232,  214,  230,  229,
      208,  208,  208,  202,  200,  198,  228,  195,  226,  192,
      221,  220,  218,  216,  106,  184,  214,  212,  211,  208,
      176,   55,  173,  202,  200,  198,   85,  167,  195,   79,
      163,  192,  190,  189,   73,  157,   69,  154,  186,  106,
      184,   63,  148,  181,  180,  144,  173,  176,   55,  173,
       52,  135,   49,  132,  130,  128,   85,  167,  124,  122,
       79,  163,  118,  116,  159,   73,  157,   69,  154,  152,
       63,  148,  146,  145,  144,   99,   97,   52,  135,   49,

      132,  130,  128,  124,  122,  118,  116,   99,  103,  102,
       97,   59,  271,   31,   31,   15,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271
    } ;

static yyconst flex_int16_t yy_chk[655] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,    5,    6,   76,    5,    6,    3,   26,    4,
       26,    5,    6,   13,   13,   27,   27,   76,   14,   14,
        9,    9,    3,   13,    4,    9,    5,    6,   14,    9,
        9,   10,   10,   11,   11,  278,   10,   12,   12,   31,
       10,   10,   31,   11,  269,   40,   11,   12,   40,  268,
       12,   17,   17,  100,   17,   19,   19,   75,   17,  100,

       17,   17,   24,   24,   17,   19,   28,   28,   75,   24,
       37,   37,   24,   42,   42,   37,   28,  267,   28,   37,
       37,   39,   39,   42,   43,  221,   42,   43,   46,   46,
      114,   39,   47,   47,   48,  221,   39,   48,   46,   39,
       51,  114,   47,   51,   52,   52,   53,   53,   54,   39,
      265,   54,   55,   55,   52,   58,   53,   56,   56,   63,
       63,   58,   55,   64,   58,   72,   64,   56,   72,   63,
      140,   63,   65,   65,   69,   69,  140,   74,   80,   69,
       74,   80,   65,   69,   69,   79,   79,   85,   85,   87,
       86,   86,   87,   95,  236,   79,   95,   85,   79,   65,

       86,   97,  106,  106,   97,  107,  116,  236,  107,  116,
      118,  118,  106,  122,  264,  118,  122,  124,  124,  118,
      118,  128,  130,  130,  128,  132,  263,  124,  132,  106,
      124,  135,  130,  142,  135,  144,  144,  148,  154,  142,
      148,  154,  142,  157,  163,  144,  157,  163,  167,  173,
      176,  167,  173,  176,  177,  179,  179,  257,  184,  255,
      177,  184,  190,  190,  253,  179,  192,  190,  195,  192,
      198,  195,  190,  198,  200,  202,  204,  200,  202,  206,
      208,  252,  204,  208,  210,  206,  209,  209,  206,  214,
      210,  252,  214,  210,  216,  216,  209,  218,  220,  251,

      218,  220,  222,  222,  216,  224,  226,  222,  224,  226,
      228,  232,  222,  228,  232,  233,  233,  234,  244,  247,
      234,  244,  247,  254,  256,  233,  254,  256,  258,  216,
      259,  259,  260,  260,  250,  259,  249,  260,  262,  258,
      259,  262,  260,  266,  270,  248,  266,  270,  272,  272,
      273,  273,  274,  274,  275,  275,  276,  276,  277,  277,
      279,  279,  280,  280,  281,  281,  282,  282,  283,  283,
      284,  284,  285,  285,  286,  286,  287,  287,  288,  288,
      289,  289,  290,  290,  291,  291,  292,  292,  293,  293,
      294,  294,  295,  295,  296,  296,  297,  297,  298,  298,

      299,  299,  300,  300,  301,  301,  302,  302,  303,  303,
      304,  304,  305,  305,  306,  306,  307,  307,  308,  308,
      309,  309,  310,  310,  311,  311,  312,  312,  313,  313,
      314,  314,  315,  315,  316,  316,  317,  317,  318,  318,
      319,  319,  320,  320,  321,  321,  322,  322,  323,  323,
      324,  324,  325,  325,  326,  326,  327,  327,  328,  328,
      329,  329,  330,  330,  331,  331,  332,  332,  333,  333,
      334,  334,  335,  335,  336,  336,  337,  337,  338,  338,
      339,  339,  340,  340,  341,  341,  342,  342,  343,  343,
      344,  344,  345,  345,  346,  346,  347,  347,  348,  348,

      349,  349,  246,  245,  243,  242,  241,  240,  238,  237,
      231,  229,  227,  225,  219,  217,  215,  213,  212,  211,
      207,  205,  203,  201,  199,  197,  196,  194,  193,  191,
      189,  188,  187,  186,  185,  183,  182,  181,  180,  178,
      175,  174,  172,  171,  170,  169,  168,  166,  165,  164,
      162,  161,  160,  159,  158,  156,  155,  153,  152,  151,
      150,  149,  147,  146,  145,  143,  141,  139,  138,  137,
      136,  134,  133,  131,  129,  127,  126,  125,  123,  121,
      120,  119,  117,  115,  113,  112,  111,  110,  109,  108,
      105,  104,  103,  102,  101,   98,   96,   94,   93,   92,

       91,   89,   88,   83,   82,   78,   77,   66,   62,   59,
       57,   25,   15,    8,    7,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[32] =
    {   0,
0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 
    1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jscript_massager.l"

#line 45 "jscript_massager.l"
// STANDALONE is for interactive testing and debugging.
// #define STANDALONE
#ifndef STANDALONE
#undef YY_INPUT
#define YY_INPUT(a,b,c) (b = ScriptInput(a,c))

static const char *input_script_pos = NULL;
static int ScriptInput(char *buf, int max_size) {
  int result = 0;
  while (*input_script_pos && max_size) {
    max_size--;
    result++;
    *buf++ = *input_script_pos++;
  }
  return result;
}
#endif // ifndef STANDALONE. Otherwise use standard input.

#undef ECHO
#define ECHO ScriptOutput(yytext)

enum State {
  NORMAL,
  OPTIONS_ONLY, // After options(...
  OPTIONS_ITEM, // After options.item(...
  OPTIONS_DEFAULT_VALUE, // After options.defaultValue(...
};

struct StackEntry {
  StackEntry(State a_state)
      : state(a_state), assigned(false), paren_count(0) {
  } 
  std::string buffer;
  State state;
  bool assigned;
  int paren_count;
};
static std::vector<StackEntry> stack;
static const char *input_filename = NULL;
static int input_lineno = 1;
static std::string output;

static StackEntry &GetStackTop() {
  ASSERT(!stack.empty());
  return *(stack.end() - 1);
}

static State GetState() {
  return stack.empty() ? NORMAL : GetStackTop().state;  
}

static void ScriptOutput(const char *str) {
  if (GetState() != NORMAL)
    GetStackTop().buffer += str;
  else
    output += str;
}

static void PushState(State state) {
  stack.push_back(StackEntry(state));
}

static int GetParenCount() {
  return GetStackTop().paren_count;
}

static void IncreaseParenCount() {
  GetStackTop().paren_count++;
}

static void DecreaseParenCount() {
  GetStackTop().paren_count--;
}

static bool IsAssigned() {
  return GetStackTop().assigned;
}

static void SetAssigned() {
  GetStackTop().assigned = true;
}

// NOTE: This function compares strings case-Sensitively.
static void ReplaceLast(const char *src, const char *dest) {
  std::string &buffer = GetStackTop().buffer;
  size_t pos = buffer.find_last_of(src);
  if (pos != buffer.npos)
    buffer.replace(pos, strlen(src), dest);
}

// NOTE: This function compares strings case-INSensitively.
static void ReplaceFirst(const char *src, const char *dest) {
  std::string &buffer = GetStackTop().buffer;
  size_t srclen = strlen(src);
  if (buffer.size() > srclen) {
    size_t upper_bound = buffer.size() - srclen;
    for (size_t i = 0; i < upper_bound; i++) {
      if (strncasecmp(buffer.c_str() + i, src, srclen) == 0) {
        buffer.replace(i, srclen, dest);
        break;
      }
    }
  }
}

static void PopState() {
  if (IsAssigned()) {
    ScriptOutput(")");
    switch (GetState()) {
      case OPTIONS_ONLY:
        ReplaceFirst("(", ".putValue(");
        break;
      case OPTIONS_ITEM:
        ReplaceFirst("item", "putValue");
        break;
      case OPTIONS_DEFAULT_VALUE:
        ReplaceFirst("defaultValue", "putDefaultValue");
        break;
      default:
        ASSERT(false);
        break;
    }
  }
  std::string buffer = GetStackTop().buffer;
  stack.pop_back();
  ScriptOutput(buffer.c_str());
}

static void PopAllPairedStates() {
  while (!stack.empty() && GetParenCount() == 0)
    PopState();
}

static void PopAllStates() {
  while (!stack.empty())
    PopState();
}







#line 901 "jscript_massager.cc"

#define INITIAL 0
#define STR 1
#define SSTR 2
#define COMMENT 3
#define OPTIONS 4
#define AFTER_OPTIONS_PARAM 5
#define ASSIGN_RIGHT 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 195 "jscript_massager.l"


#line 1061 "jscript_massager.cc"

	if ( (yy_init) )
		{
		(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 272 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 616 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_more_len); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 197 "jscript_massager.l"
ECHO;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 198 "jscript_massager.l"
ECHO; BEGIN(STR);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 199 "jscript_massager.l"
ECHO; BEGIN(INITIAL);
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 200 "jscript_massager.l"
ECHO; BEGIN(INITIAL); // Unterminated string.
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 201 "jscript_massager.l"
ECHO;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 203 "jscript_massager.l"
ECHO;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 204 "jscript_massager.l"
ECHO; BEGIN(SSTR);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 205 "jscript_massager.l"
ECHO; BEGIN(INITIAL);
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 206 "jscript_massager.l"
ECHO; BEGIN(INITIAL); // Unterminated string.
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 207 "jscript_massager.l"
ECHO;
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 209 "jscript_massager.l"
ECHO;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 211 "jscript_massager.l"
ECHO;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 213 "jscript_massager.l"
{  // "options" is always case-sensitive.
  BEGIN(OPTIONS);
  yymore();
}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 218 "jscript_massager.l"
{
  BEGIN(INITIAL);
  PushState(OPTIONS_ONLY);
  ECHO;
  IncreaseParenCount();
}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 225 "jscript_massager.l"
{
  // "item" is case-insensitive.
  BEGIN(INITIAL);
  PushState(OPTIONS_ITEM);
  ECHO;
  IncreaseParenCount();
}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 233 "jscript_massager.l"
{
  BEGIN(INITIAL);
  PushState(OPTIONS_DEFAULT_VALUE);
  ECHO;
  IncreaseParenCount();
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 240 "jscript_massager.l"
ECHO; BEGIN(INITIAL);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 242 "jscript_massager.l"
{
  ECHO;
  if (GetState() != NORMAL)
    IncreaseParenCount();
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 248 "jscript_massager.l"
{
  PopAllPairedStates();
  ECHO;
  if (GetState() != NORMAL) {
    DecreaseParenCount();
    if (yytext[0] == ')' && GetParenCount() == 0 && !IsAssigned())
      BEGIN(AFTER_OPTIONS_PARAM);
  }
}
	YY_BREAK
case 20:
/* rule 20 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 258 "jscript_massager.l"
{
  // Mathes ...= but not ...==.
  ECHO;
  LOG("Warning: %s:%d: Old JScript grammar: %s. Converted to %s",
      input_filename, input_lineno + yylineno - 1, GetStackTop().buffer.c_str(),
      GetState() == OPTIONS_DEFAULT_VALUE ? "putDefaultValue()" : "putValue()");
  ReplaceLast(")", ",");
  ReplaceLast("=", "");
  SetAssigned();
  BEGIN(ASSIGN_RIGHT);
}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 270 "jscript_massager.l"
{
  BEGIN(INITIAL);
  PopState();
  unput(yytext[0]);
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 276 "jscript_massager.l"
{
  // Avoid [,\n] rule in this case.
  ECHO;
  BEGIN(INITIAL);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 282 "jscript_massager.l"
{
  BEGIN(INITIAL);
  unput(yytext[0]);
}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 287 "jscript_massager.l"
ECHO; // Statement should continue.
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 288 "jscript_massager.l"
ECHO; // BINARY_OP doesn't include '/' which is specially treated.
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 289 "jscript_massager.l"
ECHO; // Statement should continue.
	YY_BREAK
case 27:
/* rule 27 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 290 "jscript_massager.l"
ECHO; // Distinguish comments from the '/' operator.
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 292 "jscript_massager.l"
{
  // JavaScript allow lines not ended with ';'.
  PopAllPairedStates();
  ECHO;
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 298 "jscript_massager.l"
{
  // JScript allows ';' between '}' and 'else', which is invalid in standard JS.
  LOG("Warning: %s:%d: Old JScript grammar: %s",
      input_filename, input_lineno + yylineno - 1, yytext);
  std::string text(yytext);
  text[text.find(';')] = ' ';
  ScriptOutput(text.c_str());
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(SSTR):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(OPTIONS):
case YY_STATE_EOF(AFTER_OPTIONS_PARAM):
case YY_STATE_EOF(ASSIGN_RIGHT):
#line 307 "jscript_massager.l"
{
  if (GetState() != NORMAL) {
    LOG("WARNING: %s: File contains unpaired '(', '[' or '{'s.",
        input_filename);
    PopAllStates();
  }
  yyterminate();
}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 316 "jscript_massager.l"
ECHO;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 318 "jscript_massager.l"
ECHO;
	YY_BREAK
#line 1420 "jscript_massager.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 272 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 272 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 271);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yy_str )
{
    
	return yy_scan_bytes(yy_str,strlen(yy_str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * bytes, int  len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
    	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
    	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#undef YY_NEW_FILE
#undef YY_FLUSH_BUFFER
#undef yy_set_bol
#undef yy_new_buffer
#undef yy_set_interactive
#undef yytext_ptr
#undef YY_DO_BEFORE_ACTION

#ifdef YY_DECL_IS_OURS
#undef YY_DECL_IS_OURS
#undef YY_DECL
#endif
#line 318 "jscript_massager.l"



#ifdef STANDALONE

int main() {
  filename = "stdin";
  while (yylex());
  printf("OUTPUT:\n%s", output.c_str());
}

#else // ifdef STANDALONE

std::string MassageJScript(const char *input,
                           const char *filename, int lineno) {
  input_script_pos = input; 
  input_filename = filename;
  input_lineno = lineno;
  output.clear();

  while (yylex());
  return output;
}

END_NS // namespace smjs
END_NS // namespace ggadget

#endif // else STANDALONE

